package it.unibo.apice.oop.p13advanced.enums.en2;

public enum Regione {
	ABRUZZO, BASILICATA, CALABRIA, CAMPANIA, EMILIA_ROMAGNA, 
	FRIULI_VENEZIA_GIULIA, LAZIO, LIGURIA, LOMBARDIA, MARCHE, 
	MOLISE, PIEMONTE, PUGLIA, SARDEGNA, SICILIA, TOSCANA,
	TRENTINO_ALTO_ADIGE, UMBRIA, VALLE_D_AOSTA,	VENETO;
}

class A {
	void m() {
		Regione r = Regione.ABRUZZO;
	}
}
