package it.unibo.apice.oop.p14io.trans;

public class CPersona implements java.io.Serializable {

	// Generated by Eclipse
	private static final long serialVersionUID = -8985026380526620812L;

	private String nome;
	private int annoNascita;
	private boolean sposato;
	transient private String cachedToString = null;

	public CPersona(String nome, int annoNascita, boolean sposato) {
		this.nome = nome;
		this.annoNascita = annoNascita;
		this.sposato = sposato;
	}

	public String getNome() {
		return nome;
	}

	public int getAnnoNascita() {
		return annoNascita;
	}

	public boolean isSposato() {
		return sposato;
	}

	public void setNome(final String nome) {
		this.nome = nome;
		this.cachedToString = null;
	}

	public void setAnnoNascita(final int annoNascita) {
		this.annoNascita = annoNascita;
		this.cachedToString = null;
	}

	public void setSposato(final boolean sposato) {
		this.sposato = sposato;
		this.cachedToString = null;
	}

	private String computeToString() {
		return this.nome + ":" + this.annoNascita + ":"
				+ (this.sposato ? "spos" : "non-spos");
	}

	public String toString() {
		if (this.cachedToString == null) {
			System.err.println("Log: The cache is empty...");
			this.cachedToString = this.computeToString();
		}
		return this.cachedToString;
	}
}